### ISSUE TITLE
Wind RTPC Control script not triggering change. 

### ISSUE THREAD

**Issue by DGN4053** [balandinodidonato/Sound_Design_Internship_21_22#40]
I created this script in order to address the RTPCs of the WindGenerator11 wwise audio source plugin.
![WindRTPCControlScriptNONFUNC](https://user-images.githubusercontent.com/106657019/177760771-cb5414aa-9a95-4480-9403-614dda54e22c.png)
However when passing through the trigger object nothing occurs. 
The Object the script is on contains a box collider, set to is trigger and the script.

**Comment by DGN4053** [comment]
This is still an issue, I compared against work from Intermediate Interactive Audio and made one change. (See Below) without any effect
![BDIssue1](https://user-images.githubusercontent.com/106657019/180017763-0b040d03-4bdf-4112-a0ae-13051af518d1.png)
![BDIssue2](https://user-images.githubusercontent.com/106657019/180017770-0eb78ed9-1584-4879-93dc-a2094ee72b12.png)

The debug line did not trigger even when the if statement was removed and the box collider was in contact with objects.

**Comment by balandinodidonato** [comment]
Nothing happens because the variable does not contain any numeric variable. You have to set a value of the variable before passing them to SetRTPCValue. WindGainLeft2 etc, doe not have any value right now.

**Comment by DGN4053** [comment]
Apologies, an unhelpful screenshot had been uploaded. This has been corrected now.
The values are serialised so they display in the unity Inspector, to allow for easy script reuse. 

So unless I need to tell it to read the values, I do not see why this would not function as it is now?

Also regardless of wwise functions shouldn't the Debug.Log have been posting whenever the player object entered the box collider?

**Comment by Modestas95** [comment]
Your box colliders are not being triggered because you did not set the layer of your game object (WindControlObject in your case) to be as 'Collider'. You can do that in the top right corner of your game object Inspector.

**Comment by DGN4053** [comment]
Thank you for catching this it has been fixed now!

**Comment by balandinodidonato** [comment]
Apologies for the delay I was on leave. I'm happy that it got sorted.
