### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by DGN4053** [balandinodidonato/Sound_Design_Internship_21_22#46]
After pulling the repository a kernel error is occurring.
It reads MultiScaleVODownsampling1 not found.
![image](https://user-images.githubusercontent.com/106657019/181914190-efbe33c6-a497-45d4-abbd-f54a0cd0e228.png)

Does any one know what change caused this, as nothing I have done could have done this to the level?

**Comment by balandinodidonato** [comment]
Apologies for the delay I was on leave. I'm happy that it got sorted.
